<?php
/**
 * @file
 * Provides TREZOR connect functionality.
 */

require_once 'trezor_connect.helpers.inc';
require_once 'trezor_connect.user.inc';
require_once 'trezor_connect.forms.inc';
require_once 'trezor_connect.register.inc';
require_once 'trezor_connect.login.inc';
require_once 'trezor_connect.cron.inc';
require_once 'trezor_connect.theme.inc';

/**
 * Implements hook_permission().
 */
function trezor_connect_permission() {
  $output = array();

  $output[TREZOR_CONNECT_PERMISSION] = array(
    'title' => t('Administer TREZOR Connect'),
    'description' => t('Administer TREZOR connect functionality.'),
  );

  $output[TREZOR_CONNECT_PERMISSION_USE] = array(
    'title' => t('Use TREZOR Connect'),
    'description' => t('Use TREZOR connect functionality.'),
  );

  return $output;
}

/**
 * Implements hook_menu().
 */
function trezor_connect_menu() {
  $output = array();

  $output[TREZOR_CONNECT_PREFIX] = array(
    'title' => 'TREZOR Connect',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('trezor_connect_admin_form'),
    'access arguments' => array(TREZOR_CONNECT_PERMISSION),
    'file' => 'trezor_connect.admin.inc',
  );

  $output[TREZOR_CONNECT_PREFIX . '/settings'] = array(
    'title' => 'Settings',
    'description' => 'Configure TREZOR connect settings.',
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );

  $output[TREZOR_CONNECT_URL_REGISTER] = array(
    'title' => 'Register',
    'page callback' => 'trezor_connect_page_callback_register',
    'access arguments' => array(TREZOR_CONNECT_PERMISSION_USE),
    'type' => MENU_CALLBACK,
  );

  $output[TREZOR_CONNECT_URL_LOGIN] = array(
    'title' => 'Login',
    'page callback' => 'trezor_connect_page_callback_login',
    'access arguments' => array(TREZOR_CONNECT_PERMISSION_USE),
    'type' => MENU_CALLBACK,
  );

  $output[TREZOR_CONNECT_URL_MANAGE] = array(
    'title' => 'Authenticated Devices',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('trezor_connect_manage_form', 1),
    'access arguments' => array(TREZOR_CONNECT_PERMISSION_USE),
    'type' => MENU_LOCAL_TASK,
    'weight' => 5,
    'file' => 'trezor_connect.manage.inc',
  );

  $output[TREZOR_CONNECT_URL_MANAGE_JS] = array(
    'title' => 'Manage',
    'page callback' => 'trezor_connect_page_callback_manage',
    'page arguments' => array(1),
    'access arguments' => array(TREZOR_CONNECT_PERMISSION_USE),
    'type' => MENU_CALLBACK,
    'file' => 'trezor_connect.manage.inc',
  );

  $output[TREZOR_CONNECT_URL_MANAGE . '/forget'] = array(
    'title' => 'Forget Authenticated Devices',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('trezor_connect_forget_form', 1),
    'access arguments' => array(TREZOR_CONNECT_PERMISSION_USE),
    'type' => MENU_CALLBACK,
    'weight' => 0,
    'file' => 'trezor_connect.manage.inc',
  );

  return $output;
}
